"""paper deployments and status notes

Revision ID: 8333ffdaacba
Revises: 2ee9e2c6346e
Create Date: 2026-10-01 00:43:40.471137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8333ffdaacba'
down_revision: Union[str, None] = '2ee9e2c6346e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_deployments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('strategy_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'stopped', name='deploymentstatus'), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('commission_pct', sa.Float(), nullable=False),
    sa.Column('sizer_percents', sa.Float(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('strategies', sa.Column('status_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'status_note')
    op.drop_table('paper_deployments')
    # Postgres ENUM types survive DROP TABLE (see initial migration).
    sa.Enum(name='deploymentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
