"""paper trading account, positions, trades and orders

Revision ID: c4d1e8f7a2b9
Revises: 8333ffdaacba
Create Date: 2026-10-06 00:00:00.000000

Hand-written rather than autogenerated: the development database is populated
via the test fixture's ``create_all`` and was never stamped, so autogenerate
would either diff against a schema that is missing ``strategies.status_note``
or produce an empty revision. Every statement below is explicit.

``paper_deployments.cash`` is deliberately left untouched — it stays the
immutable configured capital from the deploy request. The new ``balance`` and
``realized_pnl`` columns carry the mutable virtual-account state, backfilled
from ``cash`` so a deployment created before this revision opens with a
consistent account.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d1e8f7a2b9'
down_revision: Union[str, None] = '8333ffdaacba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # 1. Extend paper_deployments with the mutable virtual-account state.
    #    Added nullable-with-server-default first so the backfill below can
    #    run on pre-existing rows, then tightened to NOT NULL.
    # ------------------------------------------------------------------ #
    op.add_column(
        'paper_deployments',
        sa.Column('balance', sa.Float(), nullable=True, server_default='0'),
    )
    op.add_column(
        'paper_deployments',
        sa.Column('realized_pnl', sa.Float(), nullable=True, server_default='0'),
    )
    op.add_column('paper_deployments', sa.Column('last_bar_date', sa.DateTime(), nullable=True))
    op.add_column('paper_deployments', sa.Column('last_error', sa.Text(), nullable=True))

    # Seed the account from the configured capital it was deployed with.
    op.execute('UPDATE paper_deployments SET balance = cash WHERE balance IS NULL')
    op.execute('UPDATE paper_deployments SET realized_pnl = 0 WHERE realized_pnl IS NULL')

    op.alter_column('paper_deployments', 'balance', nullable=False, server_default=None)
    op.alter_column('paper_deployments', 'realized_pnl', nullable=False, server_default=None)

    # ------------------------------------------------------------------ #
    # 2. paper_positions — one OPEN position per deployment + symbol.
    # ------------------------------------------------------------------ #
    op.create_table(
        'paper_positions',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('deployment_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('avg_entry_price', sa.Float(), nullable=False),
        sa.Column('last_price', sa.Float(), nullable=True),
        sa.Column('opened_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['deployment_id'], ['paper_deployments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'deployment_id', 'symbol', name='uq_paper_positions_deployment_symbol',
        ),
        sa.CheckConstraint('quantity > 0', name='ck_paper_positions_quantity_positive'),
        sa.CheckConstraint(
            'avg_entry_price >= 0', name='ck_paper_positions_entry_price_non_negative',
        ),
        sa.CheckConstraint(
            'last_price IS NULL OR last_price >= 0',
            name='ck_paper_positions_last_price_non_negative',
        ),
    )
    op.create_index(
        op.f('ix_paper_positions_deployment_id'), 'paper_positions', ['deployment_id'],
        unique=False,
    )

    # ------------------------------------------------------------------ #
    # 3. paper_trades — the durable ledger of CLOSED paper trades.
    # ------------------------------------------------------------------ #
    op.create_table(
        'paper_trades',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('deployment_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('direction', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('entry_price', sa.Float(), nullable=False),
        sa.Column('exit_price', sa.Float(), nullable=False),
        sa.Column('entry_date', sa.DateTime(), nullable=False),
        sa.Column('exit_date', sa.DateTime(), nullable=False),
        sa.Column('gross_pnl', sa.Float(), nullable=False),
        sa.Column('commission', sa.Float(), nullable=False),
        sa.Column('net_pnl', sa.Float(), nullable=False),
        sa.Column('won', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['deployment_id'], ['paper_deployments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            "direction IN ('long', 'short')", name='ck_paper_trades_direction',
        ),
        sa.CheckConstraint('quantity > 0', name='ck_paper_trades_quantity_positive'),
        sa.CheckConstraint(
            'entry_price >= 0 AND exit_price >= 0',
            name='ck_paper_trades_prices_non_negative',
        ),
        # Keeps the stored ledger self-consistent: net is always what was
        # booked. A tolerance rather than `=` so float64 rounding of the two
        # legs can never trip the constraint.
        sa.CheckConstraint(
            'abs(net_pnl - (gross_pnl - commission)) < 0.000001',
            name='ck_paper_trades_net_matches_gross',
        ),
    )
    op.create_index(
        op.f('ix_paper_trades_deployment_id'), 'paper_trades', ['deployment_id'],
        unique=False,
    )

    # ------------------------------------------------------------------ #
    # 4. paper_orders — audit trail of simulated BUY/SELL orders.
    #    Plain constrained strings, so no custom Postgres ENUM type is
    #    introduced and downgrade needs no explicit type drop.
    # ------------------------------------------------------------------ #
    op.create_table(
        'paper_orders',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('deployment_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('side', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('order_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('filled_at', sa.DateTime(), nullable=True),
        sa.Column('fill_price', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['deployment_id'], ['paper_deployments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("side IN ('buy', 'sell')", name='ck_paper_orders_side'),
        sa.CheckConstraint(
            "order_type IN ('market', 'limit', 'stop')", name='ck_paper_orders_order_type',
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'filled', 'rejected', 'cancelled')",
            name='ck_paper_orders_status',
        ),
        sa.CheckConstraint('quantity > 0', name='ck_paper_orders_quantity_positive'),
    )
    op.create_index(
        op.f('ix_paper_orders_deployment_id'), 'paper_orders', ['deployment_id'],
        unique=False,
    )

    # Trading ledgers are read newest-first per account.
    op.create_index(
        'ix_paper_trades_deployment_exit', 'paper_trades', ['deployment_id', 'exit_date'],
        unique=False,
    )
    op.create_index(
        'ix_paper_orders_deployment_created', 'paper_orders', ['deployment_id', 'created_at'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index('ix_paper_orders_deployment_created', table_name='paper_orders')
    op.drop_index('ix_paper_trades_deployment_exit', table_name='paper_trades')
    op.drop_index(op.f('ix_paper_orders_deployment_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_trades_deployment_id'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_positions_deployment_id'), table_name='paper_positions')
    op.drop_table('paper_orders')
    op.drop_table('paper_trades')
    op.drop_table('paper_positions')

    op.drop_column('paper_deployments', 'last_error')
    op.drop_column('paper_deployments', 'last_bar_date')
    op.drop_column('paper_deployments', 'realized_pnl')
    op.drop_column('paper_deployments', 'balance')
    # No custom ENUM types were created by this revision, so nothing to drop
    # here — unlike the two earlier revisions.